// @ts-nocheck — file ini hanya dipakai Prisma CLI (bukan kode app). Beberapa
// build (mis. Vercel) tetap meng-type-check file ini & gagal resolve type
// "prisma/config"; mematikan type-check di sini menghindari error build.
// This file was generated by Prisma, and assumes you have installed the following:
// npm install prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrasi & introspeksi memakai koneksi DIRECT (session-mode, port 5432).
    // Koneksi pooled (pgbouncer) tidak cocok untuk migrasi.
    url: process.env["DIRECT_URL"],
  },
});
