// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrasi & introspeksi memakai koneksi DIRECT (session-mode, port 5432).
    // Koneksi pooled (pgbouncer) tidak cocok untuk migrasi.
    url: process.env["DIRECT_URL"],
  },
});
